/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run generate-types script to regenerate this file.
 */

export type WebSocketCommandSchema = Command | Response | Event | Subscribe | Unsubscribe;

export interface Command {
  type: 'command';
  request_id: string;
  session_id: string;
  data: {
    command_type:
      | 'browser_state'
      | 'page_control'
      | 'dom_operation'
      | 'user_action'
      | 'highlight'
      | 'container_operation';
    action: string;
    parameters?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
}
export interface Response {
  type: 'response';
  request_id: string;
  success: boolean;
  data?: {
    [k: string]: unknown;
  };
  error?: string | null;
  [k: string]: unknown;
}
export interface Event {
  type: 'event';
  topic: string;
  session_id: string;
  data?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Subscribe {
  type: 'subscribe';
  request_id: string;
  session_id: string;
  data: {
    topics: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Unsubscribe {
  type: 'unsubscribe';
  request_id: string;
  session_id: string;
  data: {
    topics: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
