import fs from 'fs';
import path from 'path';
import { compile } from 'json-schema-to-typescript';

const schemaPath = path.resolve('docs/arch/ws-api/schema.json');
const outputPath = path.resolve('services/browser-service/types/ws-types.d.ts');

async function generate() {
  try {
    const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8'));
    const ts = await compile(schema, 'WebSocketProtocol', {
      bannerComment: '/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run generate-types script to regenerate this file.\n */',
      style: { singleQuote: true }
    });
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, ts);
    console.log(`Generated ${outputPath}`);
  } catch (err) {
    console.error('Failed to generate types:', err);
    process.exit(1);
  }
}

generate();
