# 微博 MCP 系统配置文件
system:
  name: "weibo-mcp-system"
  version: "1.0.0"
  logLevel: "info"
  dataDir: "./data"
  tempDir: "./temp"

# MCP 服务配置
mcp:
  server:
    port: 3000
    host: "localhost"
  auth:
    enabled: false
    apiKey: ""

# 浏览器配置
browser:
  pool:
    minInstances: 1
    maxInstances: 5
    timeout: 30000
  camoufox:
    headless: false
    antiDetection: true
    userAgent: "random"
    defaultTimeout: 30000

# 存储配置
storage:
  database:
    type: "sqlite"
    path: "./data/weibo.db"
  pipeline:
    framework: "local"
    models:
      text: "local-text-model"
      vision: "local-vision-model"
      maxConcurrency: 3
  deduplication:
    enabled: true
    checkByUrl: true
    checkByContent: false
    similarityThreshold: 0.9
  media:
    download: true
    maxFileSize: "50MB"
    allowedTypes: ["jpg", "png", "gif", "mp4", "mov"]

# 任务配置
tasks:
  scheduler:
    maxConcurrent: 3
    retryAttempts: 3
    cleanupInterval: 3600
  defaults:
    timeout: 1800
    maxComments: 1000
    expandComments: true

# 监控配置
monitoring:
  enabled: true
  interval: 30
  notifications:
    webhook: ""
    aiAnalysis: false

# AI 配置
ai:
  enabled: true
  provider: "local"
  pipeline:
    textProcessor: "local-text-processor"
    visionProcessor: "local-vision-processor"
    maxConcurrency: 2
    timeout: 30000
  models:
    default: "local-llm"
    vision: "local-vision-model"
    maxTokens: 4000
    temperature: 0.7

# Webhook 配置
webhook:
  enabled: false
  url: ""
  headers: {}
  timeout: 10000

# UnderConstruction 配置
underConstruction:
  enabled: true
  module: "rcc-underconstruction"
  placeholderMessage: "功能正在开发中"